#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 09-01-13 01:01 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schools.nyc.gov/DOE.Services.Geography/GeoSupportService_v1_0", TypeName="AddressInfo")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class AddressInfo
    {
        
        /// <remarks/>
        private string houseNumber;
        
        /// <remarks/>
        private string streetName;
        
        /// <remarks/>
        private string boroughOrZipCode;
        
        public AddressInfo()
        {
        }
        
        public AddressInfo(string houseNumber, string streetName, string boroughOrZipCode)
        {
            this.houseNumber = houseNumber;
            this.streetName = streetName;
            this.boroughOrZipCode = boroughOrZipCode;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0, ElementName="HouseNumber")]
        public string HouseNumber
        {
            get
            {
                return this.houseNumber;
            }
            set
            {
                if ((this.houseNumber != value))
                {
                    this.houseNumber = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1, ElementName="StreetName")]
        public string StreetName
        {
            get
            {
                return this.streetName;
            }
            set
            {
                if ((this.streetName != value))
                {
                    this.streetName = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2, ElementName="BoroughOrZipCode")]
        public string BoroughOrZipCode
        {
            get
            {
                return this.boroughOrZipCode;
            }
            set
            {
                if ((this.boroughOrZipCode != value))
                {
                    this.boroughOrZipCode = value;
                }
            }
        }
    }
}
