#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 09-01-13 01:01 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schools.nyc.gov/DOE.Services.Geography/GeoSupportService_v1_0", TypeName="AddressRange")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class AddressRange
    {
        
        /// <remarks/>
        private string lowHouseNumberDisplay;
        
        /// <remarks/>
        private string highHouseNumberDisplay;
        
        /// <remarks/>
        private Borough7DigitStreetCode borough7DigitStreetCode;
        
        /// <remarks/>
        private BuildingIdentificationNumber buildingIdentificationNumber;
        
        /// <remarks/>
        private string sideOFStreetIndicator;
        
        /// <remarks/>
        private string addressType;
        
        public AddressRange()
        {
        }
        
        public AddressRange(string lowHouseNumberDisplay, string highHouseNumberDisplay, Borough7DigitStreetCode borough7DigitStreetCode, BuildingIdentificationNumber buildingIdentificationNumber, string sideOFStreetIndicator, string addressType)
        {
            this.lowHouseNumberDisplay = lowHouseNumberDisplay;
            this.highHouseNumberDisplay = highHouseNumberDisplay;
            this.borough7DigitStreetCode = borough7DigitStreetCode;
            this.buildingIdentificationNumber = buildingIdentificationNumber;
            this.sideOFStreetIndicator = sideOFStreetIndicator;
            this.addressType = addressType;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0, ElementName="LowHouseNumberDisplay")]
        public string LowHouseNumberDisplay
        {
            get
            {
                return this.lowHouseNumberDisplay;
            }
            set
            {
                if ((this.lowHouseNumberDisplay != value))
                {
                    this.lowHouseNumberDisplay = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1, ElementName="HighHouseNumberDisplay")]
        public string HighHouseNumberDisplay
        {
            get
            {
                return this.highHouseNumberDisplay;
            }
            set
            {
                if ((this.highHouseNumberDisplay != value))
                {
                    this.highHouseNumberDisplay = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2, ElementName="Borough7DigitStreetCode")]
        public Borough7DigitStreetCode Borough7DigitStreetCode
        {
            get
            {
                return this.borough7DigitStreetCode;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("Borough7DigitStreetCode");
                }
                if ((this.borough7DigitStreetCode != value))
                {
                    this.borough7DigitStreetCode = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3, ElementName="BuildingIdentificationNumber")]
        public BuildingIdentificationNumber BuildingIdentificationNumber
        {
            get
            {
                return this.buildingIdentificationNumber;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("BuildingIdentificationNumber");
                }
                if ((this.buildingIdentificationNumber != value))
                {
                    this.buildingIdentificationNumber = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4, ElementName="SideOFStreetIndicator")]
        public string SideOFStreetIndicator
        {
            get
            {
                return this.sideOFStreetIndicator;
            }
            set
            {
                if ((this.sideOFStreetIndicator != value))
                {
                    this.sideOFStreetIndicator = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5, ElementName="AddressType")]
        public string AddressType
        {
            get
            {
                return this.addressType;
            }
            set
            {
                if ((this.addressType != value))
                {
                    this.addressType = value;
                }
            }
        }
    }
}
