#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 09-01-13 01:01 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schools.nyc.gov/DOE.Services.Geography/GeoSupportService_v1_0", TypeName="Borough5DigitStreetCode")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class Borough5DigitStreetCode
    {
        
        /// <remarks/>
        private string boroughCode;
        
        /// <remarks/>
        private string fiveDigitStreetCode;
        
        public Borough5DigitStreetCode()
        {
        }
        
        public Borough5DigitStreetCode(string boroughCode, string fiveDigitStreetCode)
        {
            this.boroughCode = boroughCode;
            this.fiveDigitStreetCode = fiveDigitStreetCode;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0, ElementName="BoroughCode")]
        public string BoroughCode
        {
            get
            {
                return this.boroughCode;
            }
            set
            {
                if ((this.boroughCode != value))
                {
                    this.boroughCode = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1, ElementName="FiveDigitStreetCode")]
        public string FiveDigitStreetCode
        {
            get
            {
                return this.fiveDigitStreetCode;
            }
            set
            {
                if ((this.fiveDigitStreetCode != value))
                {
                    this.fiveDigitStreetCode = value;
                }
            }
        }
    }
}
