#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 27-10-15 01:27 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schools.nyc.gov/DOE.Services.Geography/GeoSupportService_v1_0", TypeName="CityInfoDeptOfHealth")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class CityInfoDeptOfHealth
    {
        
        /// <remarks/>
        private string healthArea;
        
        /// <remarks/>
        private string healthCenterDistrict;
        
        public CityInfoDeptOfHealth()
        {
        }
        
        public CityInfoDeptOfHealth(string healthArea, string healthCenterDistrict)
        {
            this.healthArea = healthArea;
            this.healthCenterDistrict = healthCenterDistrict;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0, ElementName="HealthArea")]
        public string HealthArea
        {
            get
            {
                return this.healthArea;
            }
            set
            {
                if ((this.healthArea != value))
                {
                    this.healthArea = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1, ElementName="HealthCenterDistrict")]
        public string HealthCenterDistrict
        {
            get
            {
                return this.healthCenterDistrict;
            }
            set
            {
                if ((this.healthCenterDistrict != value))
                {
                    this.healthCenterDistrict = value;
                }
            }
        }
    }
}
