#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 27-10-15 01:27 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schools.nyc.gov/DOE.Services.Geography/GeoSupportService_v1_0", TypeName="CityInfoNYPD")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class CityInfoNYPD
    {
        
        /// <remarks/>
        private string nYPD_ID;
        
        /// <remarks/>
        private string policePatrolBoroughCommand;
        
        /// <remarks/>
        private string policePrecinct;
        
        public CityInfoNYPD()
        {
        }
        
        public CityInfoNYPD(string nYPD_ID, string policePatrolBoroughCommand, string policePrecinct)
        {
            this.nYPD_ID = nYPD_ID;
            this.policePatrolBoroughCommand = policePatrolBoroughCommand;
            this.policePrecinct = policePrecinct;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0, ElementName="NYPD_ID")]
        public string NYPD_ID
        {
            get
            {
                return this.nYPD_ID;
            }
            set
            {
                if ((this.nYPD_ID != value))
                {
                    this.nYPD_ID = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1, ElementName="PolicePatrolBoroughCommand")]
        public string PolicePatrolBoroughCommand
        {
            get
            {
                return this.policePatrolBoroughCommand;
            }
            set
            {
                if ((this.policePatrolBoroughCommand != value))
                {
                    this.policePatrolBoroughCommand = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2, ElementName="PolicePrecinct")]
        public string PolicePrecinct
        {
            get
            {
                return this.policePrecinct;
            }
            set
            {
                if ((this.policePrecinct != value))
                {
                    this.policePrecinct = value;
                }
            }
        }
    }
}
