#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 27-10-15 01:27 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schools.nyc.gov/DOE.Services.Geography/GeoSupportService_v1_0", TypeName="CityInfoFDNY")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class CityInfoFDNY
    {
        
        /// <remarks/>
        private string fDNY_ID;
        
        /// <remarks/>
        private string fireBattalion;
        
        /// <remarks/>
        private string fireCompanyNumber;
        
        /// <remarks/>
        private string fireCompanyType;
        
        /// <remarks/>
        private string fireDivision;
        
        public CityInfoFDNY()
        {
        }
        
        public CityInfoFDNY(string fDNY_ID, string fireBattalion, string fireCompanyNumber, string fireCompanyType, string fireDivision)
        {
            this.fDNY_ID = fDNY_ID;
            this.fireBattalion = fireBattalion;
            this.fireCompanyNumber = fireCompanyNumber;
            this.fireCompanyType = fireCompanyType;
            this.fireDivision = fireDivision;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0, ElementName="FDNY_ID")]
        public string FDNY_ID
        {
            get
            {
                return this.fDNY_ID;
            }
            set
            {
                if ((this.fDNY_ID != value))
                {
                    this.fDNY_ID = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1, ElementName="FireBattalion")]
        public string FireBattalion
        {
            get
            {
                return this.fireBattalion;
            }
            set
            {
                if ((this.fireBattalion != value))
                {
                    this.fireBattalion = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2, ElementName="FireCompanyNumber")]
        public string FireCompanyNumber
        {
            get
            {
                return this.fireCompanyNumber;
            }
            set
            {
                if ((this.fireCompanyNumber != value))
                {
                    this.fireCompanyNumber = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=3, ElementName="FireCompanyType")]
        public string FireCompanyType
        {
            get
            {
                return this.fireCompanyType;
            }
            set
            {
                if ((this.fireCompanyType != value))
                {
                    this.fireCompanyType = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=4, ElementName="FireDivision")]
        public string FireDivision
        {
            get
            {
                return this.fireDivision;
            }
            set
            {
                if ((this.fireDivision != value))
                {
                    this.fireDivision = value;
                }
            }
        }
    }
}
