#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 11-12-12 02:19 PM
//
// This source code was auto-generated by WSCF, Version=0.6.6034.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schools.nyc.gov/DOE.Services.Geography/GeoSupportService_v1_0", TypeName="EnrollmentInformationByAddressResults")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class EnrollmentInformationByAddressResults
    {
        /// <remarks/>
        private GeographicInformationByAddressResults geographicInfo;
        /// <remarks/>
        private PoliticalInfo politicalInfo;
        /// <remarks/>
        private EnrollmentInformationByAddressResultsEnrollmentInfoByAddressSchoolInfo schoolInfo;
        
        public EnrollmentInformationByAddressResults()
        {
        }

        public EnrollmentInformationByAddressResults(GeographicInformationByAddressResults geographicInfo, PoliticalInfo politicalInfo, EnrollmentInformationByAddressResultsEnrollmentInfoByAddressSchoolInfo schoolInfo )
        {
            this.geographicInfo = geographicInfo;
            this.politicalInfo = politicalInfo;
            this.schoolInfo = schoolInfo;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0, ElementName = "GeographicInfo")]
        public GeographicInformationByAddressResults GeographicInfo
        {
            get
            {
                return this.geographicInfo;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("GeographicInfo");
                }
                if ((this.geographicInfo != value))
                {
                    this.geographicInfo = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1, ElementName = "PoliticalInfo")]
        public PoliticalInfo PoliticalInfo
        {
            get
            {
                return this.politicalInfo;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("PoliticalInfo");
                }
                if ((this.politicalInfo != value))
                {
                    this.politicalInfo = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2, ElementName = "SchoolInfo")]
        public EnrollmentInformationByAddressResultsEnrollmentInfoByAddressSchoolInfo SchoolInfo
        {
            get
            {
                return this.schoolInfo;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("SchoolInfo");
                }
                if ((this.schoolInfo != value))
                {
                    this.schoolInfo = value;
                }
            }
        }
    }
}
