#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 09-01-13 01:01 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schools.nyc.gov/DOE.Services.Geography/GeoSupportService_v1_0", TypeName="GeographicInformationByIntersectionResults")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class GeographicInformationByIntersectionResults
    {
        
        /// <remarks/>
        private string geoSupportFunctionName;
        
        /// <remarks/>
        private string duplicateIntersectionCount;
        
        /// <remarks/>
        private string crossStreetCount;
        
        /// <remarks/>
        private System.Collections.Generic.List<Borough5DigitStreetCode> crossStreets;
        
        /// <remarks/>
        private string lionNodeNumber;
        
        /// <remarks/>
        private string x;
        
        /// <remarks/>
        private string y;
        
        /// <remarks/>
        private string marbleHillRikersIslandFlag;
        
        /// <remarks/>
        private CommunityDistrict communityDistrict;
        
        /// <remarks/>
        private string zipCode;
        
        /// <remarks/>
        private string schoolDistrict;
        
        /// <remarks/>
        private string censusTract2000;
        
        /// <remarks/>
        private string assemblyDistrict;
        
        /// <remarks/>
        private string congressionalDistrict;
        
        /// <remarks/>
        private string senateDistrict;
        
        /// <remarks/>
        private ErrorMessage errorMessage;
        
        public GeographicInformationByIntersectionResults()
        {
        }
        
        public GeographicInformationByIntersectionResults(
                    string geoSupportFunctionName, 
                    string duplicateIntersectionCount, 
                    string crossStreetCount, 
                    System.Collections.Generic.List<Borough5DigitStreetCode> crossStreets, 
                    string lionNodeNumber, 
                    string x, 
                    string y, 
                    string marbleHillRikersIslandFlag, 
                    CommunityDistrict communityDistrict, 
                    string zipCode, 
                    string schoolDistrict, 
                    string censusTract2000, 
                    string assemblyDistrict, 
                    string congressionalDistrict, 
                    string senateDistrict, 
                    ErrorMessage errorMessage)
        {
            this.geoSupportFunctionName = geoSupportFunctionName;
            this.duplicateIntersectionCount = duplicateIntersectionCount;
            this.crossStreetCount = crossStreetCount;
            this.crossStreets = crossStreets;
            this.lionNodeNumber = lionNodeNumber;
            this.x = x;
            this.y = y;
            this.marbleHillRikersIslandFlag = marbleHillRikersIslandFlag;
            this.communityDistrict = communityDistrict;
            this.zipCode = zipCode;
            this.schoolDistrict = schoolDistrict;
            this.censusTract2000 = censusTract2000;
            this.assemblyDistrict = assemblyDistrict;
            this.congressionalDistrict = congressionalDistrict;
            this.senateDistrict = senateDistrict;
            this.errorMessage = errorMessage;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0, ElementName="GeoSupportFunctionName")]
        public string GeoSupportFunctionName
        {
            get
            {
                return this.geoSupportFunctionName;
            }
            set
            {
                if ((this.geoSupportFunctionName != value))
                {
                    this.geoSupportFunctionName = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1, ElementName="DuplicateIntersectionCount")]
        public string DuplicateIntersectionCount
        {
            get
            {
                return this.duplicateIntersectionCount;
            }
            set
            {
                if ((this.duplicateIntersectionCount != value))
                {
                    this.duplicateIntersectionCount = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2, ElementName="CrossStreetCount")]
        public string CrossStreetCount
        {
            get
            {
                return this.crossStreetCount;
            }
            set
            {
                if ((this.crossStreetCount != value))
                {
                    this.crossStreetCount = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=3, ElementName="CrossStreets")]
        public System.Collections.Generic.List<Borough5DigitStreetCode> CrossStreets
        {
            get
            {
                return this.crossStreets;
            }
            set
            {
                if ((this.crossStreets != value))
                {
                    this.crossStreets = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4, ElementName="LionNodeNumber")]
        public string LionNodeNumber
        {
            get
            {
                return this.lionNodeNumber;
            }
            set
            {
                if ((this.lionNodeNumber != value))
                {
                    this.lionNodeNumber = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5, ElementName="X")]
        public string X
        {
            get
            {
                return this.x;
            }
            set
            {
                if ((this.x != value))
                {
                    this.x = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6, ElementName="Y")]
        public string Y
        {
            get
            {
                return this.y;
            }
            set
            {
                if ((this.y != value))
                {
                    this.y = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7, ElementName="MarbleHillRikersIslandFlag")]
        public string MarbleHillRikersIslandFlag
        {
            get
            {
                return this.marbleHillRikersIslandFlag;
            }
            set
            {
                if ((this.marbleHillRikersIslandFlag != value))
                {
                    this.marbleHillRikersIslandFlag = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8, ElementName="CommunityDistrict")]
        public CommunityDistrict CommunityDistrict
        {
            get
            {
                return this.communityDistrict;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("CommunityDistrict");
                }
                if ((this.communityDistrict != value))
                {
                    this.communityDistrict = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=9, ElementName="ZipCode")]
        public string ZipCode
        {
            get
            {
                return this.zipCode;
            }
            set
            {
                if ((this.zipCode != value))
                {
                    this.zipCode = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=10, ElementName="SchoolDistrict")]
        public string SchoolDistrict
        {
            get
            {
                return this.schoolDistrict;
            }
            set
            {
                if ((this.schoolDistrict != value))
                {
                    this.schoolDistrict = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=11, ElementName="CensusTract2000")]
        public string CensusTract2000
        {
            get
            {
                return this.censusTract2000;
            }
            set
            {
                if ((this.censusTract2000 != value))
                {
                    this.censusTract2000 = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=12, ElementName="AssemblyDistrict")]
        public string AssemblyDistrict
        {
            get
            {
                return this.assemblyDistrict;
            }
            set
            {
                if ((this.assemblyDistrict != value))
                {
                    this.assemblyDistrict = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=13, ElementName="CongressionalDistrict")]
        public string CongressionalDistrict
        {
            get
            {
                return this.congressionalDistrict;
            }
            set
            {
                if ((this.congressionalDistrict != value))
                {
                    this.congressionalDistrict = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=14, ElementName="SenateDistrict")]
        public string SenateDistrict
        {
            get
            {
                return this.senateDistrict;
            }
            set
            {
                if ((this.senateDistrict != value))
                {
                    this.senateDistrict = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=15, ElementName="ErrorMessage")]
        public ErrorMessage ErrorMessage
        {
            get
            {
                return this.errorMessage;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("ErrorMessage");
                }
                if ((this.errorMessage != value))
                {
                    this.errorMessage = value;
                }
            }
        }
    }
}
