#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 09-01-13 01:01 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    public interface IGeoSupportServiceSoap
    {
        
        GeographicInformationByAddressResults[] GeographicInformationbyAddress(string HouseNumber, string StreetName, string BoroughOrZipCode);
        
        PropertyLevelInformationByAddressResults PropertyLevelInformationbyAddress(string HouseNumber, string StreetName, string Borough);
        
        GeographicInformationByIntersectionResults GeographicInformationbyIntersection(string StreetName1, string Borough1, string StreetName2, string Borough2);
        
        ZoneInfoByAddressResultsZoneInfoByAddress[] ZoneInformationByAddress(AddressInfo zoneInformationByAddress1);
        
        EnrollmentInformationByAddressResultsEnrollmentInfoByAddress[] EnrollmentInformationByAddress(AddressInfo enrollmentInformationByAddress1);
    }
}
