#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 09-01-13 01:01 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schools.nyc.gov/DOE.Services.Geography/GeoSupportService_v1_0", TypeName="LionKey")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class LionKey
    {
        
        /// <remarks/>
        private string boroughCode;
        
        /// <remarks/>
        private string blockFaceCode;
        
        /// <remarks/>
        private string sequenceNumber;
        
        public LionKey()
        {
        }
        
        public LionKey(string boroughCode, string blockFaceCode, string sequenceNumber)
        {
            this.boroughCode = boroughCode;
            this.blockFaceCode = blockFaceCode;
            this.sequenceNumber = sequenceNumber;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0, ElementName="BoroughCode")]
        public string BoroughCode
        {
            get
            {
                return this.boroughCode;
            }
            set
            {
                if ((this.boroughCode != value))
                {
                    this.boroughCode = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1, ElementName="BlockFaceCode")]
        public string BlockFaceCode
        {
            get
            {
                return this.blockFaceCode;
            }
            set
            {
                if ((this.blockFaceCode != value))
                {
                    this.blockFaceCode = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2, ElementName="SequenceNumber")]
        public string SequenceNumber
        {
            get
            {
                return this.sequenceNumber;
            }
            set
            {
                if ((this.sequenceNumber != value))
                {
                    this.sequenceNumber = value;
                }
            }
        }
    }
}
