#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 27-10-15 01:27 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schools.nyc.gov/DOE.Services.Geography/GeoSupportService_v1_0", TypeName="NYCInformationByAddressResultsNYCInformationByAddress")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class NYCInformationByAddressResultsNYCInformationByAddress
    {
        
        /// <remarks/>
        private GeographicInformationByAddressResults geographicInfo;
        
        /// <remarks/>
        private PoliticalInfo politicalInfo;
        
        /// <remarks/>
        private NYCInformationByAddressResultsNYCInformationByAddressSchoolInfo schoolInfo;
        
        /// <remarks/>
        private CityInfo cityInfo;
        
        public NYCInformationByAddressResultsNYCInformationByAddress()
        {
        }
        
        public NYCInformationByAddressResultsNYCInformationByAddress(GeographicInformationByAddressResults geographicInfo, PoliticalInfo politicalInfo, NYCInformationByAddressResultsNYCInformationByAddressSchoolInfo schoolInfo, CityInfo cityInfo)
        {
            this.geographicInfo = geographicInfo;
            this.politicalInfo = politicalInfo;
            this.schoolInfo = schoolInfo;
            this.cityInfo = cityInfo;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0, ElementName="GeographicInfo")]
        public GeographicInformationByAddressResults GeographicInfo
        {
            get
            {
                return this.geographicInfo;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("GeographicInfo");
                }
                if ((this.geographicInfo != value))
                {
                    this.geographicInfo = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1, ElementName="PoliticalInfo")]
        public PoliticalInfo PoliticalInfo
        {
            get
            {
                return this.politicalInfo;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("PoliticalInfo");
                }
                if ((this.politicalInfo != value))
                {
                    this.politicalInfo = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2, ElementName="SchoolInfo")]
        public NYCInformationByAddressResultsNYCInformationByAddressSchoolInfo SchoolInfo
        {
            get
            {
                return this.schoolInfo;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("SchoolInfo");
                }
                if ((this.schoolInfo != value))
                {
                    this.schoolInfo = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3, ElementName="CityInfo")]
        public CityInfo CityInfo
        {
            get
            {
                return this.cityInfo;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("CityInfo");
                }
                if ((this.cityInfo != value))
                {
                    this.cityInfo = value;
                }
            }
        }
    }
}
