#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 09-01-13 01:01 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schools.nyc.gov/DOE.Services.Geography/GeoSupportService_v1_0", TypeName="PoliticalInfo")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class PoliticalInfo
    {
        
        /// <remarks/>
        private string houseCode;
        
        /// <remarks/>
        private string segmentID;
        
        /// <remarks/>
        private string standardizedStreetName;
        
        /// <remarks/>
        private string streetCodeB10SC;
        
        /// <remarks/>
        private string zipCode;
        
        /// <remarks/>
        private string censusTract2010;
        
        /// <remarks/>
        private string censusBlock2010;
        
        /// <remarks/>
        private string municipalCourtDistrict;
        
        /// <remarks/>
        private string cityCouncilDistrict;
        
        public PoliticalInfo()
        {
        }
        
        public PoliticalInfo(string houseCode, string segmentID, string standardizedStreetName, string streetCodeB10SC, string zipCode, string censusTract2010, string censusBlock2010, string municipalCourtDistrict, string cityCouncilDistrict)
        {
            this.houseCode = houseCode;
            this.segmentID = segmentID;
            this.standardizedStreetName = standardizedStreetName;
            this.streetCodeB10SC = streetCodeB10SC;
            this.zipCode = zipCode;
            this.censusTract2010 = censusTract2010;
            this.censusBlock2010 = censusBlock2010;
            this.municipalCourtDistrict = municipalCourtDistrict;
            this.cityCouncilDistrict = cityCouncilDistrict;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0, ElementName="HouseCode")]
        public string HouseCode
        {
            get
            {
                return this.houseCode;
            }
            set
            {
                if ((this.houseCode != value))
                {
                    this.houseCode = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1, ElementName="SegmentID")]
        public string SegmentID
        {
            get
            {
                return this.segmentID;
            }
            set
            {
                if ((this.segmentID != value))
                {
                    this.segmentID = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2, ElementName="StandardizedStreetName")]
        public string StandardizedStreetName
        {
            get
            {
                return this.standardizedStreetName;
            }
            set
            {
                if ((this.standardizedStreetName != value))
                {
                    this.standardizedStreetName = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=3, ElementName="StreetCodeB10SC")]
        public string StreetCodeB10SC
        {
            get
            {
                return this.streetCodeB10SC;
            }
            set
            {
                if ((this.streetCodeB10SC != value))
                {
                    this.streetCodeB10SC = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=4, ElementName="ZipCode")]
        public string ZipCode
        {
            get
            {
                return this.zipCode;
            }
            set
            {
                if ((this.zipCode != value))
                {
                    this.zipCode = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=5, ElementName="CensusTract2010")]
        public string CensusTract2010
        {
            get
            {
                return this.censusTract2010;
            }
            set
            {
                if ((this.censusTract2010 != value))
                {
                    this.censusTract2010 = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=6, ElementName="CensusBlock2010")]
        public string CensusBlock2010
        {
            get
            {
                return this.censusBlock2010;
            }
            set
            {
                if ((this.censusBlock2010 != value))
                {
                    this.censusBlock2010 = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=7, ElementName="MunicipalCourtDistrict")]
        public string MunicipalCourtDistrict
        {
            get
            {
                return this.municipalCourtDistrict;
            }
            set
            {
                if ((this.municipalCourtDistrict != value))
                {
                    this.municipalCourtDistrict = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=8, ElementName="CityCouncilDistrict")]
        public string CityCouncilDistrict
        {
            get
            {
                return this.cityCouncilDistrict;
            }
            set
            {
                if ((this.cityCouncilDistrict != value))
                {
                    this.cityCouncilDistrict = value;
                }
            }
        }
    }
}
