#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 09-01-13 01:01 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schools.nyc.gov/DOE.Services.Geography/GeoSupportService_v1_0", TypeName="PropertyLevelInformationByAddressResults")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class PropertyLevelInformationByAddressResults
    {
        
        /// <remarks/>
        private string geoSupportFunctionName;
        
        /// <remarks/>
        private string lowHouseNumberSorted;
        
        /// <remarks/>
        private BoroughBlockLot boroughBlockLot;
        
        /// <remarks/>
        private string rPADSelfCheckCode;
        
        /// <remarks/>
        private string cornerCode;
        
        /// <remarks/>
        private string numberOfBuildings;
        
        /// <remarks/>
        private string numberOfBlockFaces;
        
        /// <remarks/>
        private string interiorFlag;
        
        /// <remarks/>
        private string vacantFlag;
        
        /// <remarks/>
        private string marbleHillRikersIslandFlag;
        
        /// <remarks/>
        private string addressOverflowFlag;
        
        /// <remarks/>
        private string strollKey;
        
        /// <remarks/>
        private BuildingIdentificationNumber buildingIdentificationNumber;
        
        /// <remarks/>
        private string condoFlag;
        
        /// <remarks/>
        private string condoNumber;
        
        /// <remarks/>
        private string cOOPNumber;
        
        /// <remarks/>
        private string x;
        
        /// <remarks/>
        private string y;
        
        /// <remarks/>
        private string numberOfAddresses;
        
        /// <remarks/>
        private System.Collections.Generic.List<AddressRange> alternateStreets;
        
        public PropertyLevelInformationByAddressResults()
        {
        }
        
        public PropertyLevelInformationByAddressResults(
                    string geoSupportFunctionName, 
                    string lowHouseNumberSorted, 
                    BoroughBlockLot boroughBlockLot, 
                    string rPADSelfCheckCode, 
                    string cornerCode, 
                    string numberOfBuildings, 
                    string numberOfBlockFaces, 
                    string interiorFlag, 
                    string vacantFlag, 
                    string marbleHillRikersIslandFlag, 
                    string addressOverflowFlag, 
                    string strollKey, 
                    BuildingIdentificationNumber buildingIdentificationNumber, 
                    string condoFlag, 
                    string condoNumber, 
                    string cOOPNumber, 
                    string x, 
                    string y, 
                    string numberOfAddresses, 
                    System.Collections.Generic.List<AddressRange> alternateStreets)
        {
            this.geoSupportFunctionName = geoSupportFunctionName;
            this.lowHouseNumberSorted = lowHouseNumberSorted;
            this.boroughBlockLot = boroughBlockLot;
            this.rPADSelfCheckCode = rPADSelfCheckCode;
            this.cornerCode = cornerCode;
            this.numberOfBuildings = numberOfBuildings;
            this.numberOfBlockFaces = numberOfBlockFaces;
            this.interiorFlag = interiorFlag;
            this.vacantFlag = vacantFlag;
            this.marbleHillRikersIslandFlag = marbleHillRikersIslandFlag;
            this.addressOverflowFlag = addressOverflowFlag;
            this.strollKey = strollKey;
            this.buildingIdentificationNumber = buildingIdentificationNumber;
            this.condoFlag = condoFlag;
            this.condoNumber = condoNumber;
            this.cOOPNumber = cOOPNumber;
            this.x = x;
            this.y = y;
            this.numberOfAddresses = numberOfAddresses;
            this.alternateStreets = alternateStreets;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0, ElementName="GeoSupportFunctionName")]
        public string GeoSupportFunctionName
        {
            get
            {
                return this.geoSupportFunctionName;
            }
            set
            {
                if ((this.geoSupportFunctionName != value))
                {
                    this.geoSupportFunctionName = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1, ElementName="LowHouseNumberSorted")]
        public string LowHouseNumberSorted
        {
            get
            {
                return this.lowHouseNumberSorted;
            }
            set
            {
                if ((this.lowHouseNumberSorted != value))
                {
                    this.lowHouseNumberSorted = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2, ElementName="BoroughBlockLot")]
        public BoroughBlockLot BoroughBlockLot
        {
            get
            {
                return this.boroughBlockLot;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("BoroughBlockLot");
                }
                if ((this.boroughBlockLot != value))
                {
                    this.boroughBlockLot = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3, ElementName="RPADSelfCheckCode")]
        public string RPADSelfCheckCode
        {
            get
            {
                return this.rPADSelfCheckCode;
            }
            set
            {
                if ((this.rPADSelfCheckCode != value))
                {
                    this.rPADSelfCheckCode = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4, ElementName="CornerCode")]
        public string CornerCode
        {
            get
            {
                return this.cornerCode;
            }
            set
            {
                if ((this.cornerCode != value))
                {
                    this.cornerCode = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5, ElementName="NumberOfBuildings")]
        public string NumberOfBuildings
        {
            get
            {
                return this.numberOfBuildings;
            }
            set
            {
                if ((this.numberOfBuildings != value))
                {
                    this.numberOfBuildings = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6, ElementName="NumberOfBlockFaces")]
        public string NumberOfBlockFaces
        {
            get
            {
                return this.numberOfBlockFaces;
            }
            set
            {
                if ((this.numberOfBlockFaces != value))
                {
                    this.numberOfBlockFaces = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7, ElementName="InteriorFlag")]
        public string InteriorFlag
        {
            get
            {
                return this.interiorFlag;
            }
            set
            {
                if ((this.interiorFlag != value))
                {
                    this.interiorFlag = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8, ElementName="VacantFlag")]
        public string VacantFlag
        {
            get
            {
                return this.vacantFlag;
            }
            set
            {
                if ((this.vacantFlag != value))
                {
                    this.vacantFlag = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=9, ElementName="MarbleHillRikersIslandFlag")]
        public string MarbleHillRikersIslandFlag
        {
            get
            {
                return this.marbleHillRikersIslandFlag;
            }
            set
            {
                if ((this.marbleHillRikersIslandFlag != value))
                {
                    this.marbleHillRikersIslandFlag = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=10, ElementName="AddressOverflowFlag")]
        public string AddressOverflowFlag
        {
            get
            {
                return this.addressOverflowFlag;
            }
            set
            {
                if ((this.addressOverflowFlag != value))
                {
                    this.addressOverflowFlag = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=11, ElementName="StrollKey")]
        public string StrollKey
        {
            get
            {
                return this.strollKey;
            }
            set
            {
                if ((this.strollKey != value))
                {
                    this.strollKey = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=12, ElementName="BuildingIdentificationNumber")]
        public BuildingIdentificationNumber BuildingIdentificationNumber
        {
            get
            {
                return this.buildingIdentificationNumber;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("BuildingIdentificationNumber");
                }
                if ((this.buildingIdentificationNumber != value))
                {
                    this.buildingIdentificationNumber = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=13, ElementName="CondoFlag")]
        public string CondoFlag
        {
            get
            {
                return this.condoFlag;
            }
            set
            {
                if ((this.condoFlag != value))
                {
                    this.condoFlag = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=14, ElementName="CondoNumber")]
        public string CondoNumber
        {
            get
            {
                return this.condoNumber;
            }
            set
            {
                if ((this.condoNumber != value))
                {
                    this.condoNumber = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=15, ElementName="COOPNumber")]
        public string COOPNumber
        {
            get
            {
                return this.cOOPNumber;
            }
            set
            {
                if ((this.cOOPNumber != value))
                {
                    this.cOOPNumber = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=16, ElementName="X")]
        public string X
        {
            get
            {
                return this.x;
            }
            set
            {
                if ((this.x != value))
                {
                    this.x = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=17, ElementName="Y")]
        public string Y
        {
            get
            {
                return this.y;
            }
            set
            {
                if ((this.y != value))
                {
                    this.y = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=18, ElementName="NumberOfAddresses")]
        public string NumberOfAddresses
        {
            get
            {
                return this.numberOfAddresses;
            }
            set
            {
                if ((this.numberOfAddresses != value))
                {
                    this.numberOfAddresses = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=19, ElementName="AlternateStreets")]
        public System.Collections.Generic.List<AddressRange> AlternateStreets
        {
            get
            {
                return this.alternateStreets;
            }
            set
            {
                if ((this.alternateStreets != value))
                {
                    this.alternateStreets = value;
                }
            }
        }
    }
}
