#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 09-01-13 01:01 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schools.nyc.gov/DOE.Services.Geography/GeoSupportService_v1_0", TypeName="ZonedSchools")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class ZonedSchools
    {
        
        /// <remarks/>
        private string schoolYear;
        
        /// <remarks/>
        private ZonedSchoolInfo elementarySchools;
        
        /// <remarks/>
        private ZonedSchoolInfo middleSchools;
        
        /// <remarks/>
        private ZonedSchoolInfo highSchools;
        
        public ZonedSchools()
        {
        }
        
        public ZonedSchools(string schoolYear, ZonedSchoolInfo elementarySchools, ZonedSchoolInfo middleSchools, ZonedSchoolInfo highSchools)
        {
            this.schoolYear = schoolYear;
            this.elementarySchools = elementarySchools;
            this.middleSchools = middleSchools;
            this.highSchools = highSchools;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0, ElementName="SchoolYear")]
        public string SchoolYear
        {
            get
            {
                return this.schoolYear;
            }
            set
            {
                if ((this.schoolYear != value))
                {
                    this.schoolYear = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1, ElementName="ElementarySchools")]
        public ZonedSchoolInfo ElementarySchools
        {
            get
            {
                return this.elementarySchools;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("ElementarySchools");
                }
                if ((this.elementarySchools != value))
                {
                    this.elementarySchools = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2, ElementName="MiddleSchools")]
        public ZonedSchoolInfo MiddleSchools
        {
            get
            {
                return this.middleSchools;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("MiddleSchools");
                }
                if ((this.middleSchools != value))
                {
                    this.middleSchools = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3, ElementName="HighSchools")]
        public ZonedSchoolInfo HighSchools
        {
            get
            {
                return this.highSchools;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("HighSchools");
                }
                if ((this.highSchools != value))
                {
                    this.highSchools = value;
                }
            }
        }
    }
}
