#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 09-01-13 01:01 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace GeoSupportService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schools.nyc.gov/DOE.Services.Geography/GeoSupportService_v1_0", TypeName="ZonedSchoolInfo")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class ZonedSchoolInfo
    {
        
        /// <remarks/>
        private string polygonId;
        
        /// <remarks/>
        private System.Collections.Generic.List<ZonedSchoolInfoSchoolInfo> schoolInfo;
        
        /// <remarks/>
        private string remarks;
        
        /// <remarks/>
        private string zonedDistrict;
        
        public ZonedSchoolInfo()
        {
        }
        
        public ZonedSchoolInfo(string polygonId, System.Collections.Generic.List<ZonedSchoolInfoSchoolInfo> schoolInfo, string remarks, string zonedDistrict)
        {
            this.polygonId = polygonId;
            this.schoolInfo = schoolInfo;
            this.remarks = remarks;
            this.zonedDistrict = zonedDistrict;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0, ElementName="PolygonId")]
        public string PolygonId
        {
            get
            {
                return this.polygonId;
            }
            set
            {
                if ((this.polygonId != value))
                {
                    this.polygonId = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SchoolInfo", Order=1)]
        public System.Collections.Generic.List<ZonedSchoolInfoSchoolInfo> SchoolInfo
        {
            get
            {
                return this.schoolInfo;
            }
            set
            {
                if ((this.schoolInfo != value))
                {
                    this.schoolInfo = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2, ElementName="Remarks")]
        public string Remarks
        {
            get
            {
                return this.remarks;
            }
            set
            {
                if ((this.remarks != value))
                {
                    this.remarks = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=3, ElementName="ZonedDistrict")]
        public string ZonedDistrict
        {
            get
            {
                return this.zonedDistrict;
            }
            set
            {
                if ((this.zonedDistrict != value))
                {
                    this.zonedDistrict = value;
                }
            }
        }
    }
}
